### ISSUE TITLE
Error running script with python3

### ISSUE THREAD

**Issue by Marcio861** [pwnsociety/WebForce#2]
error running python3 

python3 WebForce.py  -u "http://site.com/id=3" --all

                     .--.     v1.0.0   
            ,-.------+-.|  ,-.     
   ,--=======* )"("")===)===* )    
   �        `-"---==-+-"|  `-"     
   O                 '--'     github.com/pwnsociety 

[+] Started scanning @ 18:41:07

Traceback (most recent call last):
  File "/mnt/WebForce/WebForce.py", line 628, in <module>
    params = dict(x.split('=') for x in query.split('&'))
ValueError: dictionary update sequence element #0 has length 1; 2 is required

**Comment by a6thmfsin** [comment]
same

**Comment by prettyprincess270** [comment]
Did it work for you ? 
> same
